#Exercícios Numpy


1 - Importe a biblioteca numpy com o alias "np"

In [2]:
import numpy as np

2 - Crie um array qualquer e informe o tamanho deste vetor em memória.

In [3]:
a = np.arange(1)
a.dtype

dtype('int64')

3 - Reduza o tamanho do array anterior em memória sem alterar ou excluir nenhum dado e exiba o novo tamanho do array.

In [4]:
a.astype('int16')

array([0], dtype=int16)

4 - Crie um vetor com valores de 10 a 49

In [5]:
a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

5 - Inverta o vetor anterior

In [6]:
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

6- Crie uma matriz 3x3 com valores que variam de 0 a 8

In [7]:
a = np.zeros((3,3))
a = np.arange(9)
a = np.resize(a,(3,3))
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7- Encontre índices de elementos diferentes de zero de [1,2,0,0,4,0] (dica: tem função pronta para isso)

In [8]:
x = np.array([1,2,0,0,4,0])
np.nonzero(x)

(array([0, 1, 4]),)

8 - Crie uma matriz 10x10 com valores aleatórios e encontre os valores mínimo, máximo, média, moda e desvio padrão.

In [9]:
from scipy import stats

a = np.random.rand(10,10)
print("Max - "+str(np.max(a)))
print("min - "+str(np.min(a)))
print("mean - "+str(np.mean(a)))
print("median - "+str(np.median(a)))
vals,counts = np.unique(a, return_counts=True)
index = np.argmax(counts)
print("mode - "+str(vals[index]))
print("std - "+str(np.std(a)))


Max - 0.9986107950941664
min - 0.013577757847544114
mean - 0.4421814486127995
median - 0.3803382951725688
mode - 0.013577757847544114
std - 0.28580244509839636


9 - Dada uma matriz 1D, multiplique por 10 todos os elementos que estão entre 3 e 8.

In [10]:
a = np.arange(10)
a[(a>3) & (a<8)] *= 10
a


array([ 0,  1,  2,  3, 40, 50, 60, 70,  8,  9])

10 - Crie uma matriz 5x5 com valores de linha variando de 0 a 4

In [11]:
np.random.rand(5,5)*4

array([[0.79127505, 0.86795937, 1.72617676, 2.69081591, 0.01604605],
       [0.03651621, 1.95968654, 3.26032924, 0.16957188, 1.77566026],
       [3.71040686, 3.16445617, 2.98995463, 2.70310637, 1.27389454],
       [0.6336402 , 0.0170095 , 3.49134839, 0.89898851, 3.80420407],
       [1.45820498, 1.05130336, 2.95920084, 0.71145603, 0.14575089]])

11 - Crie um vetor de inteiros aleatório de tamanho 10 e ordene-o

In [12]:
np.random.seed(1)
a = np.random.random(10)
np.sort(a)

array([1.14374817e-04, 9.23385948e-02, 1.46755891e-01, 1.86260211e-01,
       3.02332573e-01, 3.45560727e-01, 3.96767474e-01, 4.17022005e-01,
       5.38816734e-01, 7.20324493e-01])

12 - Crie o mesmo vetor da questão anterior (com o mesmo seed) e exiba a ordem de seus índices (função argsort)

In [13]:
np.random.seed(1)
a = np.random.random(10)
a.argsort()

array([2, 5, 4, 6, 3, 7, 8, 0, 9, 1])

13 - Crie um vetor aleatório de tamanho 10 e substitua o valor máximo por 0

In [14]:
a[np.argmax(a)] = 0
a

array([4.17022005e-01, 0.00000000e+00, 1.14374817e-04, 3.02332573e-01,
       1.46755891e-01, 9.23385948e-02, 1.86260211e-01, 3.45560727e-01,
       3.96767474e-01, 5.38816734e-01])

14 - Crie uma matriz 3x3 e exiba o índice e o valor de cada posição. (dica: consulte as funções np.ndenumerate e np.ndindex)

In [15]:
a = np.random.rand(3,3)
for index, x in np.ndenumerate(a):
    print(index, x)
print("")
for index, x in np.ndindex(3,3):
    print(index, x)

(0, 0) 0.4191945144032948
(0, 1) 0.6852195003967595
(0, 2) 0.20445224973151743
(1, 0) 0.8781174363909454
(1, 1) 0.027387593197926163
(1, 2) 0.6704675101784022
(2, 0) 0.41730480236712697
(2, 1) 0.5586898284457517
(2, 2) 0.14038693859523377

0 0
0 1
0 2
1 0
1 1
1 2
2 0
2 1
2 2


15- Como ordenar uma matriz pela enésima coluna?

In [23]:
col = 1



col += -1
a = np.random.rand(3,3)
print(a)
np.sort(a[:,col])[::-1]


[[0.04995346 0.53589641 0.66379465]
 [0.51488911 0.94459476 0.58655504]
 [0.90340192 0.1374747  0.13927635]]


array([0.90340192, 0.51488911, 0.04995346])