# Introdução à biblioteca Numpy


Fontes: 

* https://numpy.org/devdocs/user/quickstart.html
* https://medium.com/ensina-ai/entendendo-a-biblioteca-numpy-4858fde63355

O NumPy é uma poderosa biblioteca Python que é usada principalmente para realizar cálculos em Arrays Multidimensionais. 

O NumPy fornece um grande conjunto de funções e operações de biblioteca que ajudam os programadores a executar facilmente cálculos numéricos. Esses tipos de cálculos numéricos são amplamente utilizados em tarefas como:

* **Modelos de Machine Learning:** ao escrever algoritmos de Machine Learning, supõe-se que se realize vários cálculos numéricos em Array. Por exemplo, multiplicação de Arrays, transposição, adição, etc. O NumPy fornece uma excelente biblioteca para cálculos fáceis (em termos de escrita de código) e rápidos (tempo de execução). Os Arrays NumPy são usados para armazenar os dados de treinamento, bem como os parâmetros dos modelos de Machine Learning.

* **Processamento de Imagem e Computação Gráfica:** imagens no computador são representadas como Arrays Multidimensionais de números. NumPy torna-se a escolha mais natural para o mesmo. O NumPy, na verdade, fornece algumas excelentes funções de biblioteca para rápida manipulação de imagens. Alguns exemplos são o espelhamento de uma imagem, a rotação de uma imagem por um determinado ângulo etc.

* **Tarefas matemáticas:** NumPy é bastante útil para executar várias tarefas matemáticas como integração numérica, diferenciação, interpolação, extrapolação e muitas outras. O NumPy possui também funções incorporadas para álgebra linear e geração de números aleatórios. É uma biblioteca que pode ser usada em conjuto do SciPy e Matplotlib. Substituindo o MATLAB quando se trata de tarefas matemáticas.


Fonte: https://medium.com/ensina-ai/entendendo-a-biblioteca-numpy-4858fde63355

A classe de array do NumPy é a ndarray, e não deve ser confudida com a classe padrão de arrays do Python, a array.array, uma vez que essa só lida com vetores unidimensionais e possui muito menos funcionalidades.

Os principais atributos da classe numpy.ndarray são:

* **ndarray.ndim**: número de dimensões;
* **ndarray.shape**: retorna uma tupla com tamanho das dimensões. Uma matriz com n linhas e m colunas vai ter o shape de (n,m). O tamanho da tupla é equivalente ao número de dimensões do array (ndarray.ndim);
* **ndarray.size**: número total de elementos no array;
* **ndarray.dtype**: retorna um objeto referente ao tipo dos elementos do array. Pode-se criar uma array com os tipos pré-definidos do Python, mas a biblioteca NumPy possui seus próprios tipos de dados, como: numpy.int32, numpy.int16 e numpy.float64.
* **ndarray.itemsize**: número de bytes de cada elemento do array;
* **ndarray.data**: retorna os elementos do array.


In [ ]:
import numpy as np

a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
print("shape: {}".format(a.shape))

print("ndim: {}".format(a.ndim))

print("itemsize: {}".format(a.itemsize))

print("size: {}".format(a.size))

print("dtype: {}".format(a.dtype.name))

print("type: {}".format(type(a)))

shape: (3, 5)
ndim: 2
itemsize: 8
size: 15
dtype: int64
type: <class 'numpy.ndarray'>


O NumPy converte todos os elementos do array para o tipo mais geral entre os seus elementos

In [ ]:
b = np.array([6, 7, 8])
print(b)
print(b.dtype.name)

b = np.array([6.1, 7, 8])
print(b)
print(b.dtype.name)

b = np.array([6.1, '7', 8])
print(b)
print(b.dtype.name)

b = np.array([6.1, 'Pós-graduação em Data Science & Analytics', 8])
print(b)
print(b.dtype.name)

b = np.array([6.1, 7, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'])
print(b)
print(b.dtype.name)

[6 7 8]
int64
[6.1 7.  8. ]
float64
['6.1' '7' '8']
str1024
['6.1' 'Pós-graduação em Data Science & Analytics' '8']
str1312
['6.1' '7'
 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.']
str14240


O tipo nulo do Numpy: numpy.nan

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.nan is np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))

nan
False
True
nan
True


## Criação de arrays

Existem diversas formas de criar arrays NumPy. Uma delas é a partir da conversão de outras estruturas de dados como listas, tuplas e dicionários. 

In [ ]:
lista = [1,2,3,4,5]
tupla = (1,2)
dicionario = {'a':1, 'b':2, 'c':3}

array_lista = np.array(lista)
array_tupla = np.array(tupla)
array_dicionario = np.array(list(dicionario.items()))

print('lista: {} ndarray:{}'.format(lista, array_lista))
print('tupla: {} ndarray:{}'.format(tupla, array_tupla))
print('dicionário: {} ndarray:{}'.format(dicionario, array_dicionario))


lista: [1, 2, 3, 4, 5] ndarray:[1 2 3 4 5]
tupla: (1, 2) ndarray:[1 2]
dicionário: {'a': 1, 'b': 2, 'c': 3} ndarray:[['a' '1']
 ['b' '2']
 ['c' '3']]


Também pode-se criar arrays bidimensionais a partir de sequências de dados.

In [ ]:
b = np.array([(1.5,2,3), (4,5,6), (4,5,0)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ],
       [4. , 5. , 0. ]])

Lembrando que não se pode criar arrays com múltiplos argumentos numéricos.

In [ ]:
#forma errada
b = np.array(1,2,3)
b

TypeError: ignored

In [ ]:
#forma correta
a = np.array([1,2,3])
a

array([1, 2, 3])

O tipo do array também pode ser especificado explicitamente



In [ ]:
print(np.array([1,2,3], dtype=complex))

[1.+0.j 2.+0.j 3.+0.j]


In [ ]:
a = np.array([1,2,3], dtype=complex)
b = np.array([1,2,3], dtype=np.int16)
c = np.array([1,2,3], dtype=np.int64)

print(a.itemsize, b.itemsize, c.itemsize)

16 2 8


É possível criar arrays vazios, com zeros, uns e com números não inicializados.

In [ ]:
print(np.zeros( (2,4,2) ),  end='\n\n')
print(np.ones( (2,4) ), end='\n\n')
print(np.random.random(size=(2,3)), end='\n\n')
print(np.empty((3,4)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[0.61306285 0.58008737 0.66964358]
 [0.64739167 0.0081891  0.08031978]]

[[3.88787767e-316 6.79038653e-313 2.37663529e-312 2.05833592e-312]
 [2.41907520e-312 2.56761491e-312 1.03977794e-312 1.06099790e-312]
 [1.08221785e-312 2.02566915e-322 0.00000000e+000 0.00000000e+000]]


In [ ]:
print(np.zeros( (2,4,3) ),  end='\n\n')

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]



Sobre os aleatórios em específico, é importante definir um seed

In [ ]:
np.random.seed(0)
print(np.random.random(5), end='\n\n')

np.random.seed(1)
print(np.random.random(5), end='\n\n')

np.random.seed(0)
print(np.random.random(5), end='\n\n')

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]

[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01
 1.46755891e-01]

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]



Nesse [link](https://docs.scipy.org/doc/numpy-1.15.1/reference/routines.random.html) você encontra diversas outras funções que a biblioteca Numpy oferece para geração de sequências de números aleatórios seguindo os mais diversos padrões.

O NumPy também possui a função **arange()** para gerar sequências numéricas de forma análoga à função **range()**, mas que retorna um array ao invés de uma lista.

In [ ]:
print(np.arange( 10, 30, 1 ))
print(np.arange( 10, 30, .5 ))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
[10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5 15.  15.5 16.  16.5
 17.  17.5 18.  18.5 19.  19.5 20.  20.5 21.  21.5 22.  22.5 23.  23.5
 24.  24.5 25.  25.5 26.  26.5 27.  27.5 28.  28.5 29.  29.5]


Também é possível criar arrays multidimensionais a partir de sequências numéricas usando a função **reshape()**.

In [ ]:
print("1-D")
print(np.arange(6),end='\n\n')

print("2-D")
print(np.arange(12).reshape(4,3),end='\n\n')

print("3-D")
print(np.arange(24).reshape(2,3,4),end='\n\n')

print("4-D")
print(np.arange(48).reshape(2,2,3,4),end='\n\n')

1-D
[0 1 2 3 4 5]

2-D
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

3-D
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

4-D
[[[[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]]

  [[12 13 14 15]
   [16 17 18 19]
   [20 21 22 23]]]


 [[[24 25 26 27]
   [28 29 30 31]
   [32 33 34 35]]

  [[36 37 38 39]
   [40 41 42 43]
   [44 45 46 47]]]]



Outra forma de gerar arrays de sequências numéricas cujo passo é um float é utilizando a função **linspace()** , esta que recebe como argumento o número de elementos que queremos, em vez do passo.

In [ ]:
print(np.linspace(0, 10, 5), end='\n\n')

print(np.linspace(0, np.pi*2, 10))

[ 0.   2.5  5.   7.5 10. ]

[0.         0.6981317  1.3962634  2.0943951  2.7925268  3.4906585
 4.1887902  4.88692191 5.58505361 6.28318531]


## Operações básicas

O NumPy permite a realização de operações aritméticas entre dois arrays como se fossem valores escalares.

Internamente, a biblioteca aplica a operação matemática a cada elemento do array, gerando num novo array com os valores resultantes.

In [ ]:
a = np.array( [20,30,40,50] )

b = np.arange( 4 )

c = a-b

print('A: {}'.format(a), end='\n\n')
print('B: {}'.format(b), end='\n\n')
print('C: {}'.format(a-b), end='\n\n')
print('A*B: {}'.format(a*b), end='\n\n')
print('B**2: {}'.format(b**2), end='\n\n')
print('10*sin(B): {}'.format(10*np.sin(a)), end='\n\n')
print('A<35: {}'.format(a<35))

A: [20 30 40 50]

B: [0 1 2 3]

C: [20 29 38 47]

A*B: [  0  30  80 150]

B**2: [0 1 4 9]

10*sin(B): [ 9.12945251 -9.88031624  7.4511316  -2.62374854]

A<35: [ True  True False False]


Observe que A * B não resulta no produto entre matrizes. O produto entre matrizes é obtido através do perador **@** ou com a função **dot()**

In [ ]:
a = np.array( [[1,1],[0,1]] )
b = np.array( [[2,0],[3,4]] )

print ('A * B:\n{}'.format(a * b), end='\n\n')

print ('A @ B:\n{}'.format(a @ b), end='\n\n')

print ('A @ B:\n{}'.format(a.dot(b)))

A * B:
[[2 0]
 [0 4]]

A @ B:
[[5 4]
 [3 4]]

A @ B:
[[5 4]
 [3 4]]


Também é possível utilizar operadores de atribuição com Python, como +=, -=, //=, etc. 

In [ ]:
a = np.ones((2,3), dtype=int)
b = np.random.randint(0,5, size=(2,3))
print('a:', a, end='\n\n')
print('b:', b, end='\n\n')

a *= 3

print('a *= 3:', a, end='\n\n')

b += a

print('b += a: ', b, end='\n\n')

a += b  

print('a += b: ', b, end='\n\n')

a: [[1 1 1]
 [1 1 1]]

b: [[2 4 1]
 [4 4 2]]

a *= 3: [[3 3 3]
 [3 3 3]]

b += a:  [[5 7 4]
 [7 7 5]]

a += b:  [[5 7 4]
 [7 7 5]]



E se os arrays não tiverem o mesmo número de elementos/dimensões?

**O que funciona:**

In [ ]:
a = np.array([[1,2],[3,4],[5,6],[7,8]])
b = np.array([10])

print(a)
print('A*B:\n {}'.format(a*b))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
A*B:
 [[10 20]
 [30 40]
 [50 60]
 [70 80]]


In [ ]:
a = np.array([[1,2],[3,4],[5,6],[7,8]])
b = np.array([10,20])

print('A*B:\n {}'.format(a*b))
print(b.shape, a.shape)

A*B:
 [[ 10  40]
 [ 30  80]
 [ 50 120]
 [ 70 160]]
(2,) (4, 2)


In [ ]:
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b = np.array([[10,20],[20,30]])

print('A', a)
print('\n')
print('B', b)
print('\n\n')
print('A*B:\n {}'.format(a*b))
print(a.shape, b.shape)

A [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


B [[10 20]
 [20 30]]



A*B:
 [[[ 10  40]
  [ 60 120]]

 [[ 50 120]
  [140 240]]]
(2, 2, 2) (2, 2)


**O que não funciona:**

In [ ]:
a = np.array([[1,2],[3,4],[5,6],[7,8]])
b = np.array([10,20,30])

print('A*B:\n {}'.format(a*b))

ValueError: ignored

In [ ]:
a = np.array([[1,2],[3,4],[5,6],[7,8]])
b = np.array([[10,20],[30,40]])

print(a)
print(b)
print(a.shape, b.shape)
print('A*B:\n {}'.format(a*b))


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[10 20]
 [30 40]]
(4, 2) (2, 2)


ValueError: ignored

Existem também funções da classe **ndarray** que permitem realizar operações internas com os valores do array.

In [ ]:
a = np.array([[1,2],[3,4]])
print(a, end='\n\n')

print('Somatório: {}'.format(a.sum()))
print('Produto: {}'.format(a.prod()))
print('Somatório acumulado: {}'.format(a.cumsum()))
print('Mínimo: {}'.format(a.min()))
print('Máximo: {}'.format(a.max()))
print('Média: {}'.format(a.mean()))

[[1 2]
 [3 4]]

Somatório: 10
Produto: 24
Somatório acumulado: [ 1  3  6 10]
Mínimo: 1
Máximo: 4
Média: 2.5


Além de poderem ser aplicadas a todos os dados do array, também é possível aplicar essas funções nos eixos do array.

In [ ]:
b = np.arange(12).reshape(3,4)
print('Array \n {}:'.format(b), end='\n\n')

print('Somatório por coluna: {}'.format(b.sum(axis=0)))

print('Mínimo por linha: {}'.format(b.min(axis=1)))

print('Somatório acumulado por linha: \n{}'.format(b.cumsum(axis=1)))

Array 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]:

Somatório por coluna: [12 15 18 21]
Mínimo por linha: [0 4 8]
Somatório acumulado por linha: 
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


Para conhecer todos os atributos e funções da classe ndarray clique [aqui](https://docs.scipy.org/doc/numpy-1.14.0/reference/arrays.ndarray.html).

## Funções universais

O NumPy traz um conjunto de funções universais que permitem a manipulação de arrays de diversas maneiras, como operações aritméticas, funções trigonométricas, comparação, etc. 



In [ ]:
a = np.random.randint(0, 20, 12).reshape((3,4))
b = np.random.randint(0, 20, 12).reshape((3,4))

In [ ]:
print('Array A: \n {}'.format(a))

print('Raíz quadrada: \n {}'.format(np.sqrt(a)))
print('Log: \n {}'.format(np.log(a)))


Array A: 
 [[ 1  6  7 14]
 [17  5 13  8]
 [ 9 19 16 19]]
Raíz quadrada: 
 [[1.         2.44948974 2.64575131 3.74165739]
 [4.12310563 2.23606798 3.60555128 2.82842712]
 [3.         4.35889894 4.         4.35889894]]
Log: 
 [[0.         1.79175947 1.94591015 2.63905733]
 [2.83321334 1.60943791 2.56494936 2.07944154]
 [2.19722458 2.94443898 2.77258872 2.94443898]]


In [ ]:
print('Array A: \n {}'.format(a))

print('Seno: \n {}'.format(np.sin(a)))
print('Cosseno: \n {}'.format(np.cos(a)))

print('Tangente: \n {}'.format(np.tan(a)))

Array A: 
 [[ 1  6  7 14]
 [17  5 13  8]
 [ 9 19 16 19]]
Seno: 
 [[ 0.84147098 -0.2794155   0.6569866   0.99060736]
 [-0.96139749 -0.95892427  0.42016704  0.98935825]
 [ 0.41211849  0.14987721 -0.28790332  0.14987721]]
Cosseno: 
 [[ 0.54030231  0.96017029  0.75390225  0.13673722]
 [-0.27516334  0.28366219  0.90744678 -0.14550003]
 [-0.91113026  0.98870462 -0.95765948  0.98870462]]
Tangente: 
 [[ 1.55740772 -0.29100619  0.87144798  7.24460662]
 [ 3.49391565 -3.38051501  0.46302113 -6.79971146]
 [-0.45231566  0.15158947  0.30063224  0.15158947]]


In [ ]:
print('Array A: \n {}'.format(a))
print('Array B: \n {}'.format(b))


print('Maior que: \n {}'.format(np.greater(a,b)))
print('Menor ou igual: \n {}'.format(np.less_equal(a,b)))
print('Igual: \n {}'.format(np.equal(a,b)))

Array A: 
 [[ 1  6  7 14]
 [17  5 13  8]
 [ 9 19 16 19]]
Array B: 
 [[ 5 15 15  0]
 [18  3 17 19]
 [19 19 14  7]]
Maior que: 
 [[False False False  True]
 [False  True False False]
 [False False  True  True]]
Menor ou igual: 
 [[ True  True  True False]
 [ True False  True  True]
 [ True  True False False]]
Igual: 
 [[False False False False]
 [False False False False]
 [False  True False False]]


In [ ]:
a = np.linspace(1, 10, 12)

print('Array A: \n {}'.format(a))

print('Próximo inteiro: \n {}'.format(np.ceil(a)))
print('Inteiro anterior: \n {}'.format(np.floor(a)))

Array A: 
 [ 1.          1.81818182  2.63636364  3.45454545  4.27272727  5.09090909
  5.90909091  6.72727273  7.54545455  8.36363636  9.18181818 10.        ]
Próximo inteiro: 
 [ 1.  2.  3.  4.  5.  6.  6.  7.  8.  9. 10. 10.]
Inteiro anterior: 
 [ 1.  1.  2.  3.  4.  5.  5.  6.  7.  8.  9. 10.]


Para conhecer todas as funções unversais da biblioteca Numpy clique [aqui](https://docs.scipy.org/doc/numpy-1.14.0/reference/ufuncs.html). 

## Indexação e fatiamento

Arrays de uma dimensão

In [ ]:
a = np.arange(10)**3
print('Array: {}'.format(a))

print('Terceiro elemento: {}'.format(a[2]))
print('Elementos 3, 4 e 5: {}'.format(a[2:5]))

a[:6:2] = -1000    # equivalente a a[0:6:2] = -1000

print('Array editado: {}'.format(a))
print('Vetor reverso: {}'.format(a[ : :-1] ))

Array: [  0   1   8  27  64 125 216 343 512 729]
Terceiro elemento: 8
Elementos 3, 4 e 5: [ 8 27 64]
Array editado: [-1000     1 -1000    27 -1000   125   216   343   512   729]
Vetor reverso: [  729   512   343   216   125 -1000    27 -1000     1 -1000]


In [ ]:
print('Raíz cúbica de todos os elementos')

for i in a:
  print(i**(1/3.),end=" ")

print("\n")
#De que outra forma podemos fazer essa operação?
print(a**(1/3))

Raíz cúbica de todos os elementos
nan 1.0 nan 3.0 nan 4.999999999999999 5.999999999999999 6.999999999999999 7.999999999999999 8.999999999999998 

[nan  1. nan  3. nan  5.  6.  7.  8.  9.]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in power
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: RuntimeWarning: invalid value encountered in power
  


Arrays multidimensionais

In [ ]:
b = np.random.randint(20, size=(5, 4))
b

array([[ 8, 10,  6, 11],
       [12, 11,  1,  6],
       [18,  4, 16, 15],
       [ 4,  4, 13,  0],
       [15, 11, 14, 10]])

In [ ]:
print('Array: \n{}'.format(b))

print('Célula na linha 3 e coluna 4: {}'.format(b[2,3]))

print('Coluna 2: {}'.format(b[0:5, 1] ))

print('Coluna 2 (outra forma): {}'.format(b[ : ,1] ))

print('Todas as linhas das colunas 2 e 3: \n {}'.format(b[ : ,1:3] ))

Array: 
[[ 8 10  6 11]
 [12 11  1  6]
 [18  4 16 15]
 [ 4  4 13  0]
 [15 11 14 10]]
Célula na linha 3 e coluna 4: 15
Coluna 2: [10 11  4  4 11]
Coluna 2 (outra forma): [10 11  4  4 11]
Todas as linhas das colunas 2 e 3: 
 [[10  6]
 [11  1]
 [ 4 16]
 [ 4 13]
 [11 14]]


In [ ]:
print('Array: \n{}'.format(b))

Array: 
[[ 8 10  6 11]
 [12 11  1  6]
 [18  4 16 15]
 [ 4  4 13  0]
 [15 11 14 10]]


In [ ]:
b[1,1:3]

array([11,  1])

Selecionar elementos por expressões lógicas

In [ ]:
a = np.arange(11)

print('Verificando elementos que atendem a uma condição lógica (a >= 8):',a >= 8, end="\n\n")

print('Filtrando elementos que atendem a uma condição lógica (a[a >= 8]):', a[a >= 8], end="\n\n")

a[(5 < a) & (a < 8)] *= -1
print('Editando elementos que atendem a uma condição lógica (a[(5 < a) & (a < 8)] *= -1):', a, end="\n\n")

Verificando elementos que atendem a uma condição lógica (a >= 8): [False False False False False False False False  True  True  True]

Filtrando elementos que atendem a uma condição lógica (a[a >= 8]): [ 8  9 10]

Editando elementos que atendem a uma condição lógica (a[(5 < a) & (a < 8)] *= -1): [ 0  1  2  3  4  5 -6 -7  8  9 10]



In [ ]:
a = np.arange(11)

In [ ]:
a[(5 < a) & (a < 8)]

array([6, 7])

In [ ]:
a[(5 < a) & (a < 8)] *= -1
a

array([ 0,  1,  2,  3,  4,  5, -6, -7,  8,  9, 10])

In [ ]:
a = a[(5 < a) & (a < 8)] * -1
a

array([-6, -7])